<?php
    $HTML = new HTML();
?>
<!DOCTYPE html>
<html>
<head>
    <?php echo $HTML->includeCSS("main"); ?>
	<title><?php echo constant("SIDETITLE") ?></title>
</head>
<body>
<!--<div id="sliderWrap">
    <div id="openCloseIdentifier"></div>
    <div id="slider">
        <div id="sliderContent">
            Adminpanel
        </div>
        <div id="openCloseWrap">
            <a href="#" class="topMenuAction" id="topMenuImage">
                <img src="open.png" alt="open" />
            </a>
        </div>
    </div>
</div>-->