<!DOCTYPE html>
<html>
<head>
	<title><?php echo constant("SIDETITLE") ?></title>
    <script src="weebroot/js/jquery.js"></script>
    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script src="weebroot/js/tinyMCE.js"></script>
</head>
<body>
<!--<div id="sliderWrap">
    <div id="openCloseIdentifier"></div>
    <div id="slider">
        <div id="sliderContent">
            Adminpanel
        </div>
        <div id="openCloseWrap">
            <a href="#" class="topMenuAction" id="topMenuImage">
                <img src="open.png" alt="open" />
            </a>
        </div>
    </div>
</div>-->