<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="weebroot/css/main.css">
	<script type="text/javascript" src="weebroot/js/less.js"></script>
	<script type="text/javascript" src="weebroot/js/jquery.js"></script>
	<script type="text/javascript" src="weebroot/js/panel.js"></script>
	<title><?php echo constant("SIDETITLE") ?></title>
</head>
<body>
<!--<div id="sliderWrap">
    <div id="openCloseIdentifier"></div>
    <div id="slider">
        <div id="sliderContent">
            Adminpanel
        </div>
        <div id="openCloseWrap">
            <a href="#" class="topMenuAction" id="topMenuImage">
                <img src="open.png" alt="open" />
            </a>
        </div>
    </div>
</div>-->